// Generated by newcommand.js
exports.aliases = [];

exports.execute = function(bot, msg, suffix){  
  return new Promise((resolve, reject) => {
    msg.channel.sendMessage(`👌                😂
       🍆 💤  👔 🍆
                        🛢      👃
                      ⚡  8=👊 = D 💦
                 🎺       🍆                  💦 
                 👢          👢                 ${suffix}`)
      .then(resolve)
      .catch(reject);
  });
}