// Generated by newcommand.js
exports.aliases = [];

exports.execute = function(bot, msg, suffix){
  return new Promise((resolve, reject) => {
    console.log("Ran join");
    bot.Music.join(msg).then(resolve).catch(msg.channel.sendMessage.bind(msg.channel));
  });
}