// Generated by newcommand.js
exports.aliases = ["nt", "memes"];

exports.execute = function(bot, msg, suffix){  
  return new Promise((resolve) => {
    msg.channel.sendMessage("fucking ayy lad XD").catch(bot.log);
  });
}