// Generated by newcommand.js
exports.aliases = [];

exports.execute = function(bot, msg, suffix){  
  if(!suffix){
      msg.channel.sendMessage(`The prefix here is \`${bot.getPrefix(msg)}\``)
  }
  
  var prefix = suffix.split(" ")[0];
  bot.setPrefix(msg, prefix);
}