// Generated by newcommand.js
exports.aliases = ["delete", "rem"];

exports.execute = function(bot, msg, suffix){
  return new Promise((resolve, reject) => {    
    bot.Music.removeFromQueue(msg, suffix).then(resolve).catch(reject);
  });
}